config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games do
    resources :setup_steps, controller: 'game_setup_steps' do
      put :back
    end
    resources :eval_steps, controller: 'game_eval_steps' do
      put :back
    end
  end
  resources :players
  resources :setups
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/game_eval_steps_controller.rb
class GameEvalStepsController < ApplicationController
    include Wicked::Wizard

    steps :_final_generations, :_final_production, :_final_milestones_awards, :_final_tiles, :_final_score, :_confirm_evaluation

    @@setup_idx = 0

    def show
        @game = Game.find(params[:game_id])
        if params[:setup_id]
            @setup = Setup.find(params[:setup_id])
        end
        render_wizard
    end

    def update
        @game = Game.find(params[:game_id])
        case step
        when :_final_generations, :_final_milestones_awards
            @game.assign_attributes(game_params_update)
            if @game.save(context: step)
                render_wizard(@game, {context: step}, {:setup_id=>@game.setups[@@setup_idx].id})
            else
                render_wizard(@game, {context: step, status: 422})
            end
        when :_final_production, :_final_score
            @setup = @game.setups[@@setup_idx]
            @setup.assign_attributes(setup_params_update)
            if @setup.save(context: step)
                rot_setup_idx
                unless @@setup_idx==0  # more setups to do
                    forward_in_loop
                else
                    render_wizard @setup, context: step
                end
            else
                render_wizard @setup, {context: step, status: 422}
            end
        when :_final_tiles
            @setup = @game.setups[@@setup_idx]
            @setup.assign_attributes(setup_params_update)
            if @setup.save(context: step)
                rot_setup_idx
                unless @@setup_idx==0  # finished setups
                    forward_in_loop
                else
                    # forward to loop
                    render_wizard(@setup, {context: step}, {:setup_id=>@game.setups[@@setup_idx].id})
                end
            else
                render_wizard @setup, {context: step, status: 422}
            end
        end
    end

    # one step back without saving the parameters
    def back
        @game = Game.find(params[:game_id])
        case step
        when :_final_production, :_final_tiles
            @setup = @game.setups[@@setup_idx]
            unless @@setup_idx == 0
                back_in_loop
            else
                jump_to(@previous_step)
                render_wizard
            end
        when :_final_score
            @setup = @game.setups[@@setup_idx]
            unless @@setup_idx == 0
                back_in_loop
            else
                back_to_loop
            end
        when :_final_milestones_awards
            back_to_loop
        else
            jump_to(@previous_step)
            render_wizard
        end
    end    

    private
    def game_params_update
        params.require(:game).permit(:generations,
                                     milestones_attributes: [:id, :reached, :owner_id],
                                     awards_attributes: [:id, :financed, :owner_id, :second_id])
    end
    def setup_params_update
        params.require(:setup).permit(:score, :green_tiles, :city_tiles, :other_tiles,
                                      :cash_production, :steel_production, :titanium_production,
                                      :plant_production, :energy_production, :heat_production)
    end
    def rot_setup_idx
        @@setup_idx = (@@setup_idx < @game.setups.length-1) ? @@setup_idx+1 : 0
    end
    def back_in_loop
        # decrease setup idx
        @@setup_idx -= 1
        # render with new setup idx
        jump_to(step)
        render_wizard(nil, {}, {:setup_id=>@game.setups[@@setup_idx].id})
    end
    def back_to_loop
        # last setup
        @@setup_idx = @game.setups.length-1
        jump_to(@previous_step)
        render_wizard(nil, {}, {:setup_id=>@game.setups[@@setup_idx].id})
    end
    def forward_in_loop
        jump_to(step)
        render_wizard(@setup, {context: step}, {:setup_id=>@game.setups[@@setup_idx].id})
    end
end

app/helpers/game_eval_steps_helper.rb
module GameEvalStepsHelper
end

app/views/game_eval_steps/_confirm_evaluation.html.erb
<h2>Please review the following information. Is it correct?</h2>

<% unless @game.starting_player.nil? %>
    <p>Starting player: <%= @game.starting_player.name%></p>
<% end %>
<p>Expansions used: <%= @game.get_expansions_names.join(", ") %></p>
<p>Drafting: <%= @game.drafting %></p>
<% if @game.expansion_colonies %>
    <p>Colonies: <%= @game.colonies.join(", ") %></p>
<% end %>
<% milestones_prettyprint = @game.milestones.select { |m| m.reached and m.owner}.collect {|m| "#{m.name} (#{m.owner.name})" } %>
<p>Milestones: <%= milestones_prettyprint.join(", ") %></p>
<% awards_prettyprint = @game.awards.select { |a| a.financed and a.owner}.collect { |a| a.second ? "#{a.name} (#{a.owner.name}, #{a.second.name})" : "#{a.name} (#{a.owner.name})" } %>
<p>Awards: <%= awards_prettyprint.join(", ") %></p>
<p>Player setups:</p>
<%= render @game.setups%>

<%= button_to "End the game", @game, {params: {game: {end_time: Time.now, status: "finished"}}, method: :patch} %>

<div class=link_to >
    <%= link_to "Go back to editing", game_eval_steps_path(@game) %>
</div>

app/views/game_eval_steps/_final_generations.html.erb
<%= form_with model: @game, url: wizard_path do |form| %>
    <% if @game.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @game}%>
    <% end %>
    <div>
        <%= form.label :generations %><br>
        <%= form.number_field :generations, min: 1 %><br>
    </div>
    <div class=submit_button>
        <%= form.submit %>
    </div>
<% end %>

app/views/game_eval_steps/_final_milestones_awards.html.erb
<%= form_with model: @game, url: wizard_path do |form| %>
    <% if @game.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @game}%>
    <% end %>

    <p> Financed awards: </p>
    <ul>
        <%= form.fields_for :awards do |awards_form| %>
            <li>
                <%= awards_form.object.name %> was financed
                <%= awards_form.check_box :financed, {data: {forcemax: {max_num:3, group: "awards"}, checkedenable: {toggle: false, group: awards_form.object.name}}} %>
                <%= awards_form.collection_select :owner_id, @game.players.order(:name), :id, :name, {}, {disabled: !awards_form.object.financed, data: {checkedenable: {toggle: true, group: awards_form.object.name}}} %>
                <% if @game.players.size > 2 # second place %>
                    <%= awards_form.collection_select :second_id, @game.players.order(:name), :id, :name, {}, {disabled: !awards_form.object.financed, data: {checkedenable: {toggle: true, group: awards_form.object.name}}} %>
                <% end %>
            </li>
        <% end %>
    </ul>
    <p> Reached milestones: </p>
    <ul>
        <%= form.fields_for :milestones do |milestones_form| %>
            <li>
                <%= milestones_form.object.name %> was reached
                <%= milestones_form.check_box :reached, {data: {forcemax: {max_num:3, group: "milestones"}, checkedenable: {toggle: false, group: milestones_form.object.name}}}%>
                <%= milestones_form.collection_select :owner_id, @game.players.order(:name), :id, :name, {}, {disabled: !milestones_form.object.reached, data: {checkedenable: {toggle: true, group: milestones_form.object.name}}} %>
            </li>
        <% end %>
    </ul>
    <div class="submit_button">
        <%= form.submit %>
    </div>
<% end %>

<%= button_to "Back", game_eval_step_back_path(@game, @step, id: params[:id]), {method: :put} %>

app/views/game_eval_steps/_final_production.html.erb
<h1><%=@setup.player.name%>'s final production</h1>

<%= form_with model: @setup, url: wizard_path do |form| %>
    <% if @setup.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @setup}%>
    <% end %>
    
    <div>
        <%= form.label :cash_production %><br>
        <%= form.number_field :cash_production, min:-5 %><br>
    </div>               
    <div>
        <%= form.label :steel_production %><br>
        <%= form.number_field :steel_production, min:0 %><br>
    </div>       
    <div>
        <%= form.label :titanium_production %><br>
        <%= form.number_field :titanium_production, min:0 %><br>
    </div>       
    <div>
        <%= form.label :plant_production %><br>
        <%= form.number_field :plant_production, min:0 %><br>
    </div>       
    <div>
        <%= form.label :energy_production %><br>
        <%= form.number_field :energy_production, min:0 %><br>
    </div>       
    <div>
        <%= form.label :heat_production %><br>
        <%= form.number_field :heat_production, min:0 %><br>
    </div>
    <div class=submit_button>
        <%= form.submit %>
    </div>    
<% end %>

<%= button_to "Back", game_eval_step_back_path(@game, @step, id: params[:id]), {method: :put} %>

app/views/game_eval_steps/_final_score.html.erb
<h1><%=@setup.player.name%>'s final score:</h1>

<%= form_with model: @setup, url: wizard_path do |form| %>
    <% if @setup.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @setup}%>
    <% end %>
    
    <div>
        <%= form.label :score %><br>
        <%= form.number_field :score, min:1 %><br>
    </div>
    <div class="submit_button">
        <%= form.submit %>
    </div>    
<% end %>

<%= button_to "Back", game_eval_step_back_path(@game, @step, id: params[:id]), {method: :put} %>

app/views/game_eval_steps/_final_tiles.html.erb
<h1><%=@setup.player.name%>'s tiles</h1>

<%= form_with model: @setup, url: wizard_path do |form| %>
    <% if @setup.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @setup}%>
    <% end %>
    
    <div>
        <%= form.label :green_tiles %><br>
        <%= form.number_field :green_tiles, min:0 %><br>
    </div>
    <div>
        <%= form.label :city_tiles %><br>
        <%= form.number_field :city_tiles, min:0 %><br>
    </div>
    <div>
        <%= form.label :other_tiles %><br>
        <%= form.number_field :other_tiles, min:0 %><br>
    </div>    
    <div class="submit_button">
        <%= form.submit %>
    </div>    
<% end %>

<%= button_to "Back", game_eval_step_back_path(@game, @step, id: params[:id]), {method: :put} %>