config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games do
    resources :setup_steps, controller: 'game_setup_steps' do
      put :back
    end
    resources :eval_steps, controller: 'game_eval_steps' do
      put :back
    end
  end
  resources :players
  resources :setups
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id                   :integer          not null, primary key
#  generations          :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  start_time           :datetime
#  end_time             :datetime
#  status               :string           default("setting up")
#  expansion_turmoil    :boolean
#  expansion_colonies   :boolean
#  expansion_prelude    :boolean
#  expansion_venus_next :boolean
#  cap_oxygen           :integer
#  cap_ocean            :integer
#  cap_temperature      :integer
#  cap_venus            :integer
#  expansion_hellas     :boolean
#  expansion_elysium    :boolean
#  expansion_advanced   :boolean
#  drafting             :boolean
#  colonies             :text
#  starting_player_id   :integer
#

class Game < ApplicationRecord
    include Editable
    has_many :setups, dependent: :destroy
    has_many :players, through: :setups
    has_many :milestones, dependent: :destroy
    has_many :awards, dependent: :destroy
    belongs_to :starting_player, class_name: "Player", optional: true

    accepts_nested_attributes_for :milestones
    accepts_nested_attributes_for :awards
    accepts_nested_attributes_for :setups
    
    serialize :colonies, Array

    validates :setups, length: { in: 1..5 , too_long: "%{count} players is the maximum allowed",
                                            too_short: "%{count} player is the minimum required" }
    validates :milestones, :awards, length: { in: 5..6, too_long: "%{count} is the maximum allowed",
                                                        too_short: "%{count} is the minimum required" }
    validates :starting_player, presence: true, on: :_choose_starting_player
    validates :expansion_turmoil, :expansion_colonies, :expansion_prelude, :expansion_venus_next,
              :expansion_hellas, :expansion_elysium, :expansion_advanced, :drafting,
              inclusion: {in: [true, false], message: "must be a boolean"},
              if: -> {["running", "finishing", "finished"].include? status}
    validates :start_time, :starting_player, presence: true, if: -> {["running", "finishing", "finished"].include? status}
    validates :colonies, presence: true, if: -> { expansion_colonies and ["running", "finishing", "finished"].include? status}
    validates :cap_oxygen, :cap_ocean, :cap_temperature, presence: true, if: -> { ["finishing", "finished"].include? status }
    validates :end_time, :winner, presence: true, if: :finished?
    validate :time
    validate :unique_players
    validate :hellas_elysium, on: :_choose_expansions
    validates_each :milestones, :awards, on: :_choose_milestones_awards do |record, attr, values|
        if Set.new(values.collect{|v| v.name}).length < values.length
            record.errors.add(attr, "must be different from each other")
        end
    end

    def time
        if end_time.present?
            unless end_time > start_time
                errors.add(:end_time, "must be later than start time")
            end
        end
    end

    def unique_players
        if Set.new(setups.collect{|s| s.player_id}).length < setups.length
            errors.add(:players, "must be different from each other")
        end
    end

    def hellas_elysium
        if expansion_hellas and expansion_elysium
            errors.add(:expansion_hellas, "cannot be played together with Elysium")
            errors.add(:expansion_elysium, "cannot be played together with Hellas")
        end
    end

    def winner
        winner_setups = setups.where(winner: true)
        if winner_setups.length > 0
            return winner_setups[0].player
        end
        return nil
    end

    def get_expansions_names()
        # This would actually be much nicer if we had a keyed hash... And we could just check the value and append the key.
        expansions = []
        if expansion_turmoil
            expansions << "Turmoil"
        end
        if expansion_colonies
            expansions << "Colonies"
        end
        if expansion_prelude
            expansions << "Prelude"
        end
        if expansion_hellas
            expansions << "Hellas"
        end
        if expansion_elysium
            expansions << "Elysium"
        end
        if expansion_venus_next
            expansions << "Venus Next"
        end
        if expansion_advanced
            expansions << "Advanced"
        end
        return expansions
    end

    def get_available_prelude_cards()
        prelude_list = ["#P01 Allied Banks", "#P02 Aquifer Turbines", "#P03 Biofuels", "#P04 Biolab",
                        "#P05 Biosphere Support", "#P06 Business Empire", "#P07 Dome Farming", "#P08 Donation",
                        "#P09 Early Settlement", "#P10 Ecology Experts", "#P11 Excentric Sponsor", "#P12 Experimental Forest",
                        "#P13 Galilean Mining", "#P14 Great Aquifer", "#P15 Huge Asteroid", "#P16 Io Research Outpost",
                        "#P17 Loan", "#P18 Martian Industries", "#P19 Metal-rich Asteroid", "#P20 Metals Company",
                        "#P21 Mining Operations", "#P22 Mohole", "#P23 Mohole Excavation", "#P24 Nitrogen Shipment",
                        "#P25 Orbital Construction Yard", "#P26 Polar Industries", "#P27 Power Generation", "#P28 Research Network",
                        "#P29 Self-Sufficient Settlement", "#P30 Smelting Plant", "#P31 Society Support", "#P32 Supplier",
                        "#P33 Supply Drop", "#P34 UNMI Contractor", "#P35 Acquired Space Agency"]
        prelude_cards_selected_in_setup = setups.collect {|s| s.prelude_cards.collect {|k, v| v unless k=="three"}}.flatten.compact
        available_prelude_cards = prelude_list - prelude_cards_selected_in_setup
        return available_prelude_cards
    end

    def third_prelude?
        unless setups.collect{|s| s.prelude_three}.compact.length > 0
            return false
        else
            return true
        end
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
    5.times { @game.milestones.build }
    5.times { @game.awards.build }
  end

  def create
    player_ids = params[:game][:player_ids]
    @game = Game.new(game_params_create)
    5.times { @game.milestones.build }
    5.times { @game.awards.build }
    player_ids.each do |player_id|
      unless player_id.blank?
        @game.setups.build(player_id: player_id)
      end
    end
    if @game.save
      redirect_to game_setup_steps_path(@game)
    else
      render :new, status: 422
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if params[:game][:status] == "finished"
      idx_of_highest_score = @game.setups.map {|s| s[:score]}.each_with_index.max[1]
      @game.setups[idx_of_highest_score].winner = true
      unless @game.setups[idx_of_highest_score].save
        flash.now[:alert] = "Couldn't end the game!"
        redirect_to game_eval_steps_path(@game)
      end
    end
    if @game.update(game_params_update)
      if @game.setting_up?
        redirect_to game_setup_steps_path(@game)
      elsif @game.running?
        redirect_to edit_game_path(@game)
      elsif @game.finishing?
        redirect_to game_eval_steps_path(@game)
      else  # finished
        redirect_to @game
      end
    else
      render :edit, status: 422
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to root_path
  end

  private
    def game_params_create
        params.require(:game).permit()
    end

    def game_params_update
        params.require(:game).permit(:start_time, :end_time, :status, :cap_oxygen, :cap_ocean, :cap_temperature, :cap_venus, :generations,
                                     setups_attributes: [:id, :prelude_three], colonies: [])
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/edit.html.erb
<h1>Edit a game of Terraforming Mars</h1>

<% if @game.setting_up? %>
    You should not have ended up here.
    Please <div class=link_to><%= link_to "leave", game_setup_steps_path(@game)%></div>.
<% elsif @game.running? %>
    <%= form_with model: @game do |form| %>
        <% if @game.errors.any? %>
            <%= render partial: "shared/error_messages", locals: {object: @game}%>
        <% end %>
        
        <% if @game.expansion_prelude %>
            <div>
                <%= form.fields_for :setups, @game.setups.select {|s| s.company=="Valley Trust"} do |setup_form| %>
                    <li>
                        <%= setup_form.label "#{setup_form.object.player.name}'s third prelude card" %>
                        <%= setup_form.select :prelude_three, @game.get_available_prelude_cards %>
                    </li>
                <% end %>
            </div>
        <% end %>
        <% if @game.expansion_colonies %>
            <input type=button value="Colonies" data-showhide='colonies'>
            <div id="showhide" style="display:none" data-showhide='colonies'>
                <% colonies = ["Europa", "Triton", "Callisto", "Ceres", "Enceladus", "Titan", "Miranda", "Ganymede", "Luna", "Io", "Pluto"] %>
                <% colonies.each do |c| %>
                    <%= form.label c %><br>
                    <%= form.check_box :colonies, { multiple:true }, c, false %><br>
                <%end%>
            </div>
        <% end %>
        <div>
            <%= form.label :cap_oxygen %><br>
            <%= form.number_field :cap_oxygen, { min:1, data: {cap: true}} %>
        </div>
        <div>
            <%= form.label :cap_ocean %><br>
            <%= form.number_field :cap_ocean, { min:1, data: {cap: true}} %>
        </div>
        <div>
            <%= form.label :cap_temperature %><br>
            <%= form.number_field :cap_temperature, { min:1, data: {cap: true}} %>
        </div>
        <% if @game.expansion_venus_next %>
            <div>
                <%= form.label :cap_venus %><br>
                <%= form.number_field :cap_venus, min:1 %>
            </div>
        <% end %>
        <div>
            <%= form.hidden_field :status, {data: {caphidden: "status"}} %>
            <%= form.hidden_field :generations, {data: {caphidden: "generations"}}%>
        </div>
        <div class="submit_button">
            <%= form.submit nil, {data: {capsubmit: true}}%>
        </div>
    <% end %>
<%elsif @game.finishing? %>
    You should not have ended up here.
    Please <div class=link_to><%= link_to "leave", game_eval_steps_path(@game) %></div>.
<%else # has finished%>
    The game has already ended, it cannot be edited.
    <div class=link_to><%= link_to "Show", @game %></div>
<%end%>

app/views/games/index.html.erb
<h1>Terraforming Mars Tracker</h1>

<%= image_tag "header.jpg" %>
<br>
<div class="link_to">
<%= link_to "Start a new game", new_game_path%>
</div>

<br>

<div class="link_to">
<%= link_to "View all players", players_path%>
</div>

<h2>Past games</h2>

<ul style="width: 90%; height: 250px; overflow:auto">
    <% @games.reverse_each do |game| %>
        <li class="link_to">
            <%= link_to game.start_time, game%><br>
        </li>
    <%end %>
</ul>

<h2>Expansions count</h2>

<% expansions = {expansion_advanced: "Advanced", expansion_prelude: "Prelude", 
                 expansion_hellas: "Hellas", expansion_elysium: "Elysium", 
                 expansion_colonies: "Colonies", expansion_venus_next:"Venus Next", expansion_turmoil: "Turmoil"}%>
<% expansion_count = [] %>
<% expansions.each do |sym, name| %>
    <% expansion_count << [name, @games.where(sym=>true).count]%>
<% end %>
<%= pie_chart expansion_count%>

app/views/games/new.html.erb
<h1>Start a new game of Terraforming Mars</h1>

<%= form_with model: @game do |form| %>
    <% if @game.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @game}%>
    <% end %>
    
    <div>
        <%= form.label :players %><br>
        <%= form.collection_check_boxes :player_ids, Player.order(:name), :id, :name do |b|%>
            <%=b.label do%>
                <%=b.check_box%>
                <%=b.object.name%><br>                
            <%end%>
        <%end%>
        <br>
        <li class="link_to"><%= link_to "Add new player", new_player_path %></li>
    </div>
    <div class="submit_button">
        <%= form.submit %>
    </div>
<% end %>

app/views/games/show.html.erb
<% if @game.start_time %>
    <h1>Game at <%= @game.start_time %></h1>
<% else %>
    <h1>Current game</h1>
<% end %>

<p>Starting time: <%= @game.start_time %></p>
<p>End time: <%= @game.end_time %></p>
<p>Starting player: <%= @game.starting_player.name%></p>
<p>Number of generations played: <%= @game.generations %></p>
<p>Drafting: <%= @game.drafting %></p>
<p>Expansions used: <%= @game.get_expansions_names.join(", ") %></p>
<% if @game.expansion_colonies %>
    <p>Colonies: <%= @game.colonies.join(", ") %></p>
<% end %>
<p>Environment caps:</p>
<ul>
    <li>Oxygen: <%= @game.cap_oxygen %></li>
    <li>Ocean: <%= @game.cap_ocean %></li>
    <li>Temperature: <%= @game.cap_temperature %></li>
    <% if @game.expansion_venus_next %>
        <li>Venus: <%= @game.cap_venus %></li>
    <%end %>
</ul>
<% milestones_prettyprint = @game.milestones.select { |m| m.reached }.collect {|m| "#{m.name} (#{m.owner.name})" } %>
<p>Milestones: <%= milestones_prettyprint.join(", ") %></p>
<% awards_prettyprint = @game.awards.select { |a| a.financed and a.owner}.collect { |a| a.second ? "#{a.name} (#{a.owner.name}, #{a.second.name})" : "#{a.name} (#{a.owner.name})" } %>
<p>Awards: <%= awards_prettyprint.join(", ") %></p>
<p>Player setups:</p>
<ul>
    <%@game.setups.each do |setup|%>
        <li class=link_to><%= link_to Player.find(setup.player_id).name, setup_path(setup)%></li>
    <%end%>
</ul>

<ul>
    <% unless @game.finished? %>
    <li class=link_to><%= link_to "Edit", edit_game_path(@game) %></li>
    <% end %>
    <li><%= button_to "Delete", game_path(@game), {method: :delete, data: { confirm: "Are you sure?" } } %></li>
</ul>

<div class=link_to>
    <%= link_to "Back to overview", root_path %>
</div>