config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games do
    resources :setup_steps, controller: 'game_setup_steps' do
      put :back
    end
    resources :eval_steps, controller: 'game_eval_steps' do
      put :back
    end
  end
  resources :players
  resources :setups
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/game_setup_steps_controller.rb
class GameSetupStepsController < ApplicationController
    include Wicked::Wizard
    before_action :set_steps
    before_action :setup_wizard

    @@setup_idx = 0

    def show
        @game = Game.find(params[:game_id])
        if params[:setup_id]
            @setup = Setup.find(params[:setup_id])
        end
        render_wizard
    end

    def update
        @game = Game.find(params[:game_id])
        case step
        when :_choose_expansions
            if params[:game][:expansion_venus_next]=="1" and @game.milestones.count==5
                # add one more milestone + award
                @game.milestones.build
                @game.awards.build
            end
            @game.assign_attributes(game_params_update)
            if @game.save(context: step)
                render_wizard @game, context: step
            else
                render_wizard @game, {context: step, status: 422}
            end
        when :_choose_setup
            @setup = @game.setups[@@setup_idx]
            @setup.assign_attributes(setup_params_update)
            if @setup.save(context: step)
                rot_setup_idx
                unless @@setup_idx==0  # finished setups
                    jump_to(:_choose_setup)
                    render_wizard(@setup, {context: step}, {:setup_id=>@game.setups[@@setup_idx].id})
                else
                    render_wizard @setup, context: step
                end
            else
                render_wizard @setup, {context: step, status: 422}
            end
        when :_choose_milestones_awards
            @game.assign_attributes(game_params_update)
            if @game.save(context: step)
                unless @game.expansion_colonies  # go to choose_setup
                    render_wizard @game, {context: step}, {:setup_id=>@game.setups[@@setup_idx].id}
                else
                    render_wizard @game, context: step
                end
            else
                render_wizard @game, {context: step, status: 422}
            end
        when :_choose_colonies
            @game.assign_attributes(game_params_update)
            if @game.save(context: step)
                render_wizard(@game, {context: step}, {:setup_id=>@game.setups[@@setup_idx].id})
            else
                render_wizard @game, {context: step, status: 422}
            end
        else
            @game.assign_attributes(game_params_update)
            if @game.save(context: step)
                render_wizard @game, context: step
            else
                render_wizard @game, {context: step, status: 422}
            end
        end
    end

    def back
        @game = Game.find(params[:game_id])
        case step
        when :_choose_setup
            @setup = @game.setups[@@setup_idx]
            unless @@setup_idx == 0
                # decrease setup idx
                @@setup_idx -= 1
                # render with new setup idx
                jump_to(:_choose_setup)
                render_wizard(nil, {}, {:setup_id=>@game.setups[@@setup_idx].id})
            else
                jump_to(@previous_step)
                render_wizard
            end
        else
            jump_to(@previous_step)
            render_wizard
        end
    end

    private
    def game_params_update
        params.require(:game).permit(:drafting, :starting_player_id,
                                     :expansion_turmoil, :expansion_venus_next, :expansion_hellas,
                                     :expansion_elysium, :expansion_colonies, :expansion_prelude,
                                     :expansion_advanced,
                                     colonies: [], milestones_attributes: [:id, :name], awards_attributes: [:id, :name])
    end
    def setup_params_update
        params.require(:setup).permit(:company, :prelude_one, :prelude_two)
    end
    def set_steps
        @game = Game.find(params[:game_id])
        unless @game.expansion_colonies
            self.steps = [:_choose_starting_player, :_choose_expansions, :_choose_milestones_awards, :_choose_setup, :_confirm_setup]
        else
            self.steps = [:_choose_starting_player, :_choose_expansions, :_choose_milestones_awards, :_choose_colonies, :_choose_setup, :_confirm_setup]
        end
    end
    def rot_setup_idx
        @@setup_idx = (@@setup_idx < @game.setups.length-1) ? @@setup_idx+1 : 0
    end
end

app/helpers/game_setup_steps_helper.rb
module GameSetupStepsHelper
end

app/views/game_setup_steps/_choose_colonies.html.erb
<%= form_with model: @game, url: wizard_path do |form| %>
    <% if @game.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @game}%>
    <% end %>
    
    <div>
        <% colonies = ["Europa", "Triton", "Callisto", "Ceres", "Enceladus", "Titan", "Miranda", "Ganymede", "Luna", "Io", "Pluto"] %>
        <% colonies.each do |c| %>
            <%= form.check_box :colonies, { multiple:true }, c, false %>
            <%= form.label c %><br>
        <%end%>
    </div>
    <div class="submit_button">
        <%= form.submit %>
    </div>    
<% end %>

<%= button_to "Back", game_setup_step_back_path(@game, @step, id: params[:id]), {method: :put} %>

app/views/game_setup_steps/_choose_expansions.html.erb
<%= form_with model: @game, url: wizard_path do |form| %>
    <% if @game.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @game}%>
    <% end %>
    
    <div>
        <%= form.check_box :expansion_turmoil %>
        <%= form.label :expansion_turmoil %><br>
    </div>
    <div>
        <%= form.check_box :expansion_colonies %>
        <%= form.label :expansion_colonies %><br>
    </div>
    <div>
        <%= form.check_box :expansion_prelude %>
        <%= form.label :expansion_prelude %><br>
    </div>
    <div>
        <%= form.check_box :expansion_hellas, {data: {forcemax: {max_num:1, group: "hellas_elysium"}}}%>
        <%= form.label :expansion_hellas %><br>
    </div>
    <div>
        <%= form.check_box :expansion_elysium, {data: {forcemax: {max_num:1, group: "hellas_elysium"}}}%>
        <%= form.label :expansion_elysium %><br>
    </div>
    <div>
        <%= form.check_box :expansion_venus_next %>
        <%= form.label :expansion_venus_next %><br>
    </div>
    <div>
        <%= form.check_box :expansion_advanced %>
        <%= form.label :expansion_advanced %><br>
    </div>
    <div>
        <%= form.check_box :drafting %>
        <%= form.label :drafting %> <br>
    </div>
    <div class="submit_button">
        <%= form.submit %>
    </div>
<% end %>

<%= button_to "Back", game_setup_step_back_path(@game, @step, id: params[:id]), {method: :put} %>

app/views/game_setup_steps/_choose_milestones_awards.html.erb
<%= form_with model: @game, url: wizard_path do |form| %>
    <% if @game.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @game}%>
    <% end %>
    
    <p> Milestones: </p>
    <% milestones = {%>
        <%"Basic" => ["Terraformer", "Mayor", "Gardener", "Builder", "Planner"],%>
        <%"Hellas" => ["Diversifier", "Tactitian", "Polar Explorer", "Energizer", "Rim Settler"],%>
        <%"Elysium" => ["Generalist", "Specialist", "Ecologist", "Tycoon", "Legend"],%>
        <%"Venus" => ["Hoverlord"]%>
    <%}%>  
    <ul>
        <%= form.fields_for :milestones do |milestones_form| %>
            <li>
                <%= milestones_form.select :name, milestones, {selected: milestones_form.object.get_selected(milestones_form.index)} %>
            </li>
        <% end %>
    </ul>
    <p> Awards: </p>
    <% awards = {%>
        <%"Basic" => ["Landlord", "Scientist", "Banker", "Thermalist", "Miner"],%>
        <%"Hellas" => ["Cultivator", "Magnate", "Space Baron", "Excentric", "Contractor"],%>
        <%"Elysium" => [ "Celebrity", "Industrialist", "Desert Settler", "Estate Dealer", "Benefactor"],%>
        <%"Venus" => ["Venuphile"]%>
    <%}%>
    <ul>
        <%= form.fields_for :awards do |awards_form| %>
            <li>
                <%= awards_form.select :name, awards, {selected: awards_form.object.get_selected(awards_form.index)} %>
            </li>
        <% end %>
    </ul>
    <div class="submit_button">
        <%= form.submit %>
    </div>
<% end %>

<%= button_to "Back", game_setup_step_back_path(@game, @step, id: params[:id]), {method: :put} %>

app/views/game_setup_steps/_choose_setup.html.erb
<h1>Player setup for <%=@setup.player.name%></h1>

<%= form_with model: @setup, url: wizard_path, local:true do |form| %>
    <% if @setup.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @setup}%>
    <% end %>

    <div>
        <%= form.label :company %>
        <% company_options = {"Basic" => ["Starting Corporation", "Credicor", "Ecoline", "Helion", "Mining Guild", "Interplanetary Cinematics",
                                          "Inventrix", "Phobolog", "Tharsis Republic", "Thorgate", "United Nations Mars Initiative"]} %>
        <% company_options["Advanced"] = ["Teractor", "Saturn Systems"] if @setup.game.expansion_advanced %>
        <% company_options["Prelude"] = ["Cheung Shing Mars", "Point Luna", "Robinson Industries", "Valley Trust", "Vitor"] if @setup.game.expansion_prelude %>
        <% company_options["Colonies"] = ["Aridor", "Arklight", "Polyphemos", "Poseidon", "Storm Craft Incorporated"] if @setup.game.expansion_colonies %>
        <% company_options["Venus Next"] = ["Aphrodite", "Celestic", "Manutech", "Morning Star Inc", "Viron"] if @setup.game.expansion_venus_next %>
        <% company_options["Turmoil"] = ["Lakefront Resorts", "Pristar", "Septem Tribus", "Terralabs Research", "Utopia Invest"] if @setup.game.expansion_turmoil %>
        <% company_options["Promotional"] = ["Factorum", "Mons Insurance", "Philares", "Arcadian Communities", "Recyclon", "Splice Tactical Genomics"] %>
        <%= form.select :company, company_options %>
    </div>
    <% if @setup.game.expansion_prelude %>
        <div>
            <%= form.label :prelude_cards %><br>
            <% prelude_list = ["#P01 Allied Banks", "#P02 Aquifer Turbines", "#P03 Biofuels", "#P04 Biolab",
                               "#P05 Biosphere Support", "#P06 Business Empire", "#P07 Dome Farming", "#P08 Donation",
                               "#P09 Early Settlement", "#P10 Ecology Experts", "#P11 Excentric Sponsor", "#P12 Experimental Forest",
                               "#P13 Galilean Mining", "#P14 Great Aquifer", "#P15 Huge Asteroid", "#P16 Io Research Outpost",
                               "#P17 Loan", "#P18 Martian Industries", "#P19 Metal-rich Asteroid", "#P20 Metals Company",
                               "#P21 Mining Operations", "#P22 Mohole", "#P23 Mohole Excavation", "#P24 Nitrogen Shipment",
                               "#P25 Orbital Construction Yard", "#P26 Polar Industries", "#P27 Power Generation", "#P28 Research Network",
                               "#P29 Self-Sufficient Settlement", "#P30 Smelting Plant", "#P31 Society Support", "#P32 Supplier",
                               "#P33 Supply Drop", "#P34 UNMI Contractor", "#P35 Acquired Space Agency"] %>
            <%= form.select :prelude_one, prelude_list %>
            <%= form.select :prelude_two, prelude_list %>
        </div>
    <% end %>
    <div class="submit_button">
        <%= form.submit %>
    </div>    
<% end %>

<%= button_to "Back", game_setup_step_back_path(@game, @step, id: params[:id]), {method: :put} %>

app/views/game_setup_steps/_choose_starting_player.html.erb
<%= form_with model: @game, url: wizard_path do |form| %>
    <% if @game.errors.any? %>
        <%= render partial: "shared/error_messages", locals: {object: @game}%>
    <% end %>
    
    <div>
        <%= form.label :starting_player %>
        <%= form.collection_select :starting_player_id, @game.players, :id, :name %>
    </div>
    <div class="submit_button">
        <%= form.submit %>
    </div>
<% end %>

<%= button_to "Cancel", game_path(@game), { method: :delete, data: { confirm: "Are you sure?" } } %>

app/views/game_setup_steps/_confirm_setup.html.erb
<h2>Please review the following information. Is it correct?</h2>

<% unless @game.starting_player.nil? %>
    <p>Starting player: <%= @game.starting_player.name%></p>
<% end %>
<p>Expansions used: <%= @game.get_expansions_names.join(", ") %></p>
<p>Drafting: <%= @game.drafting %></p>
<% if @game.expansion_colonies %>
    <p>Colonies: <%= @game.colonies.join(", ") %></p>
<% end %>
<p>Available milestones: <%= @game.milestones.collect {|milestone| milestone.name}.join(", ") %></p>
<p>Available awards: <%= @game.awards.collect {|award| award.name}.join(", ") %></p>
<p>Player setups:</p>
<%= render @game.setups%>

<%= button_to "Start the game", @game, {params: {game: {start_time: Time.now, status: "running"}}, method: :patch} %>

<div class=link_to >
    <%= link_to "Go back to editing", game_setup_steps_path(@game) %>
</div>